import { TeamDataType } from "../types/gameTypes";

export const initialTeamsData: Array<TeamDataType> = [
  {
    name: "Arsenal",
    logoKey: "arsenal",
    formation: "3-3-4",
    teamColor: "#ff0000",
    teamSecondaryColor: "#ffffff",
    goalSoundKey: "",
    coach: {
      name: "Mikel Arteta",
      image: "",
      happyImage: "",
      sadImage: "",
    },
    defensLine: {
      speed: 2,
      compatchness: 2,
      defencStyle: "Gegenpressing",
      passingStyle: "Direct Attack",
      speedOfGame: "Spending Time",
      wingersStyle: "Follow the Attack",
    },
    midfieldLine: {
      speed: 2,
      compatchness: 2,
      defencStyle: "Gegenpressing",
      passingStyle: "Direct Attack",
      speedOfGame: "Spending Time",
      wingersStyle: "Follow the Attack",
    },
    attackLine: {
      speed: 2,
      compatchness: 2,
      defencStyle: "Gegenpressing",
      passingStyle: "Direct Attack",
      speedOfGame: "Spending Time",
      wingersStyle: "Follow the Attack",
    },
    goalKeeperSpeed: 5,
    footballers: [
      {
        name: "Bernd Leno",
        role: "GK",
        imageURL: "",
        logoKey: "",
        passAccuracy: 0,
        playerSpeed: 0,
        passSpeed: 0,
        shootAccuracy: 0,
        shootSpeed: 0,
        dribbling: 0,
        defenceStrength: 0,
        descipline: 0,
        reaction: 0,
      },
      {
        name: "David Luiz",
        role: "Defender",
        imageURL: "",
        logoKey: "",
        passAccuracy: 0,
        playerSpeed: 0,
        passSpeed: 0,
        shootAccuracy: 0,
        shootSpeed: 0,
        dribbling: 0,
        defenceStrength: 0,
        descipline: 0,
        reaction: 0,
      },
      {
        name: "Thomas Partey",
        role: "Midfielder",
        imageURL: "",
        logoKey: "",
        passAccuracy: 0,
        playerSpeed: 0,
        passSpeed: 0,
        shootAccuracy: 0,
        shootSpeed: 0,
        dribbling: 0,
        defenceStrength: 0,
        descipline: 0,
        reaction: 0,
      },
      {
        name: "Cristiano Ronaldo",
        role: "Forward",
        imageURL: "",
        logoKey: "",
        passAccuracy: 0,
        playerSpeed: 0,
        passSpeed: 0,
        shootAccuracy: 0,
        shootSpeed: 0,
        dribbling: 0,
        defenceStrength: 0,
        descipline: 0,
        reaction: 0,
      },
      {
        name: "Emile Smith Rowe",
        role: "Forward",
        imageURL: "",
        logoKey: "",
        passAccuracy: 0,
        playerSpeed: 0,
        passSpeed: 0,
        shootAccuracy: 0,
        shootSpeed: 0,
        dribbling: 0,
        defenceStrength: 0,
        descipline: 0,
        reaction: 0,
      },
      {
        name: "Bukayo Saka",
        role: "Forward",
        imageURL: "",
        logoKey: "",
        passAccuracy: 0,
        playerSpeed: 0,
        passSpeed: 0,
        shootAccuracy: 0,
        shootSpeed: 0,
        dribbling: 0,
        defenceStrength: 0,
        descipline: 0,
        reaction: 0,
      },
      {
        name: "Gabriel Martinelli",
        role: "Forward",
        imageURL: "",
        logoKey: "",
        passAccuracy: 0,
        playerSpeed: 0,
        passSpeed: 0,
        shootAccuracy: 0,
        shootSpeed: 0,
        dribbling: 0,
        defenceStrength: 0,
        descipline: 0,
        reaction: 0,
      },
      {
        name: "Kieran Tierney",
        role: "Defender",
        imageURL: "",
        logoKey: "",
        passAccuracy: 0,
        playerSpeed: 0,
        passSpeed: 0,
        shootAccuracy: 0,
        shootSpeed: 0,
        dribbling: 0,
        defenceStrength: 0,
        descipline: 0,
        reaction: 0,
      },
      {
        name: "Ben White",
        role: "Defender",
        imageURL: "",
        logoKey: "",
        passAccuracy: 0,
        playerSpeed: 0,
        passSpeed: 0,
        shootAccuracy: 0,
        shootSpeed: 0,
        dribbling: 0,
        defenceStrength: 0,
        descipline: 0,
        reaction: 0,
      },
      {
        name: "Granit Xhaka",
        role: "Midfielder",
        imageURL: "",
        logoKey: "",
        passAccuracy: 0,
        playerSpeed: 0,
        passSpeed: 0,
        shootAccuracy: 0,
        shootSpeed: 0,
        dribbling: 0,
        defenceStrength: 0,
        descipline: 0,
        reaction: 0,
      },
      {
        name: "Ruben Neves",
        role: "Forward",
        imageURL: "",
        logoKey: "",
        passAccuracy: 0,
        playerSpeed: 0,
        passSpeed: 0,
        shootAccuracy: 0,
        shootSpeed: 0,
        dribbling: 0,
        defenceStrength: 0,
        descipline: 0,
        reaction: 0,
      },
      {
        name: "Gabriel Magalhaes",
        role: "Defender",
        imageURL: "",
        logoKey: "",
        passAccuracy: 0,
        playerSpeed: 0,
        passSpeed: 0,
        shootAccuracy: 0,
        shootSpeed: 0,
        dribbling: 0,
        defenceStrength: 0,
        descipline: 0,
        reaction: 0,
      },
      {
        name: "Albert Sambi Lokonga",
        role: "Midfielder",
        imageURL: "",
        logoKey: "",
        passAccuracy: 0,
        playerSpeed: 0,
        passSpeed: 0,
        shootAccuracy: 0,
        shootSpeed: 0,
        dribbling: 0,
        defenceStrength: 0,
        descipline: 0,
        reaction: 0,
      },
    ],
  },
  {
    name: "Barselona",
    logoKey: "barselona",
    formation: "4-4-2",
    teamColor: "#ff0000",
    teamSecondaryColor: "#ffffff",
    goalSoundKey: "",
    coach: {
      name: "Mikel Arteta",
      image: "",
      happyImage: "",
      sadImage: "",
    },
    defensLine: {
      speed: 2,
      compatchness: 2,
      defencStyle: "Gegenpressing",
      passingStyle: "Direct Attack",
      speedOfGame: "Spending Time",
      wingersStyle: "Follow the Attack",
    },
    midfieldLine: {
      speed: 2,
      compatchness: 2,
      defencStyle: "Gegenpressing",
      passingStyle: "Direct Attack",
      speedOfGame: "Spending Time",
      wingersStyle: "Follow the Attack",
    },
    attackLine: {
      speed: 2,
      compatchness: 2,
      defencStyle: "Gegenpressing",
      passingStyle: "Direct Attack",
      speedOfGame: "Spending Time",
      wingersStyle: "Follow the Attack",
    },
    goalKeeperSpeed: 5,
    footballers: [
      {
        name: "Bernd Leno",
        role: "GK",
        imageURL: "",
        logoKey: "",
        passAccuracy: 0,
        playerSpeed: 0,
        passSpeed: 0,
        shootAccuracy: 0,
        shootSpeed: 0,
        dribbling: 0,
        defenceStrength: 0,
        descipline: 0,
        reaction: 0,
      },
      {
        name: "David Luiz",
        role: "Defender",
        imageURL: "",
        logoKey: "",
        passAccuracy: 0,
        playerSpeed: 0,
        passSpeed: 0,
        shootAccuracy: 0,
        shootSpeed: 0,
        dribbling: 0,
        defenceStrength: 0,
        descipline: 0,
        reaction: 0,
      },
      {
        name: "Thomas Partey",
        role: "Midfielder",
        imageURL: "",
        logoKey: "",
        passAccuracy: 0,
        playerSpeed: 0,
        passSpeed: 0,
        shootAccuracy: 0,
        shootSpeed: 0,
        dribbling: 0,
        defenceStrength: 0,
        descipline: 0,
        reaction: 0,
      },
      {
        name: "Cristiano Ronaldo",
        role: "Forward",
        imageURL: "",
        logoKey: "",
        passAccuracy: 0,
        playerSpeed: 0,
        passSpeed: 0,
        shootAccuracy: 0,
        shootSpeed: 0,
        dribbling: 0,
        defenceStrength: 0,
        descipline: 0,
        reaction: 0,
      },
      {
        name: "Emile Smith Rowe",
        role: "Forward",
        imageURL: "",
        logoKey: "",
        passAccuracy: 0,
        playerSpeed: 0,
        passSpeed: 0,
        shootAccuracy: 0,
        shootSpeed: 0,
        dribbling: 0,
        defenceStrength: 0,
        descipline: 0,
        reaction: 0,
      },
      {
        name: "Bukayo Saka",
        role: "Forward",
        imageURL: "",
        logoKey: "",
        passAccuracy: 0,
        playerSpeed: 0,
        passSpeed: 0,
        shootAccuracy: 0,
        shootSpeed: 0,
        dribbling: 0,
        defenceStrength: 0,
        descipline: 0,
        reaction: 0,
      },
      {
        name: "Gabriel Martinelli",
        role: "Forward",
        imageURL: "",
        logoKey: "",
        passAccuracy: 0,
        playerSpeed: 0,
        passSpeed: 0,
        shootAccuracy: 0,
        shootSpeed: 0,
        dribbling: 0,
        defenceStrength: 0,
        descipline: 0,
        reaction: 0,
      },
      {
        name: "Kieran Tierney",
        role: "Defender",
        imageURL: "",
        logoKey: "",
        passAccuracy: 0,
        playerSpeed: 0,
        passSpeed: 0,
        shootAccuracy: 0,
        shootSpeed: 0,
        dribbling: 0,
        defenceStrength: 0,
        descipline: 0,
        reaction: 0,
      },
      {
        name: "Ben White",
        role: "Defender",
        imageURL: "",
        logoKey: "",
        passAccuracy: 0,
        playerSpeed: 0,
        passSpeed: 0,
        shootAccuracy: 0,
        shootSpeed: 0,
        dribbling: 0,
        defenceStrength: 0,
        descipline: 0,
        reaction: 0,
      },
      {
        name: "Granit Xhaka",
        role: "Midfielder",
        imageURL: "",
        logoKey: "",
        passAccuracy: 0,
        playerSpeed: 0,
        passSpeed: 0,
        shootAccuracy: 0,
        shootSpeed: 0,
        dribbling: 0,
        defenceStrength: 0,
        descipline: 0,
        reaction: 0,
      },
      {
        name: "Ruben Neves",
        role: "Forward",
        imageURL: "",
        logoKey: "",
        passAccuracy: 0,
        playerSpeed: 0,
        passSpeed: 0,
        shootAccuracy: 0,
        shootSpeed: 0,
        dribbling: 0,
        defenceStrength: 0,
        descipline: 0,
        reaction: 0,
      },
      {
        name: "Gabriel Magalhaes",
        role: "Defender",
        imageURL: "",
        logoKey: "",
        passAccuracy: 0,
        playerSpeed: 0,
        passSpeed: 0,
        shootAccuracy: 0,
        shootSpeed: 0,
        dribbling: 0,
        defenceStrength: 0,
        descipline: 0,
        reaction: 0,
      },
      {
        name: "Albert Sambi Lokonga",
        role: "Midfielder",
        imageURL: "",
        logoKey: "",
        passAccuracy: 0,
        playerSpeed: 0,
        passSpeed: 0,
        shootAccuracy: 0,
        shootSpeed: 0,
        dribbling: 0,
        defenceStrength: 0,
        descipline: 0,
        reaction: 0,
      },
    ],
  },
];
